package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CCategorierecette generated by hbm2java
 */
@Entity
@Table(name = "c_categorierecette", catalog = "gestion_resto2")
public class CategorieRecette implements java.io.Serializable {

	private Integer idCategorie;
	private String nomCategorie;
	private Set<Recette> CRecettes = new HashSet<Recette>(0);

	public CategorieRecette() {
	}

	public CategorieRecette(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	public CategorieRecette(String nomCategorie, Set<Recette> CRecettes) {
		this.nomCategorie = nomCategorie;
		this.CRecettes = CRecettes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCategorie", unique = true, nullable = false)
	public Integer getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(Integer idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nomCategorie", nullable = false, length = 20)
	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CCategorierecette")
	public Set<Recette> getCRecettes() {
		return this.CRecettes;
	}

	public void setCRecettes(Set<Recette> CRecettes) {
		this.CRecettes = CRecettes;
	}

}
