package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pojo.common.Moderateur;

/**
 * CCommentaire generated by hbm2java
 */
@Entity
@Table(name = "c_commentaire", catalog = "gestion_resto2")
public class Commentaire implements java.io.Serializable {

	private Integer idCommentaire;
	private Moderateur moderateur;
	private Recette CRecette;
	private Membre CMembre;
	private String commentaire;
	private Date dateInsertion;
	private byte statut;

	public Commentaire() {
	}

	public Commentaire(Moderateur moderateur, Recette CRecette,
			Membre CMembre, String commentaire, Date dateInsertion, byte statut) {
		this.moderateur = moderateur;
		this.CRecette = CRecette;
		this.CMembre = CMembre;
		this.commentaire = commentaire;
		this.dateInsertion = dateInsertion;
		this.statut = statut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommentaire", unique = true, nullable = false)
	public Integer getIdCommentaire() {
		return this.idCommentaire;
	}

	public void setIdCommentaire(Integer idCommentaire) {
		this.idCommentaire = idCommentaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersonne", nullable = false)
	public Moderateur getModerateur() {
		return this.moderateur;
	}

	public void setModerateur(Moderateur moderateur) {
		this.moderateur = moderateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecette", nullable = false)
	public Recette getCRecette() {
		return this.CRecette;
	}

	public void setCRecette(Recette CRecette) {
		this.CRecette = CRecette;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idMembre", nullable = false)
	public Membre getCMembre() {
		return this.CMembre;
	}

	public void setCMembre(Membre CMembre) {
		this.CMembre = CMembre;
	}

	@Column(name = "commentaire", nullable = false)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateInsertion", nullable = false, length = 19)
	public Date getDateInsertion() {
		return this.dateInsertion;
	}

	public void setDateInsertion(Date dateInsertion) {
		this.dateInsertion = dateInsertion;
	}

	@Column(name = "statut", nullable = false)
	public byte getStatut() {
		return this.statut;
	}

	public void setStatut(byte statut) {
		this.statut = statut;
	}

}
