package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CDetailrecetteId generated by hbm2java
 */
@Embeddable
public class DetailRecetteId implements java.io.Serializable {

	private int idIngredient;
	private int idRecette;

	public DetailRecetteId() {
	}

	public DetailRecetteId(int idIngredient, int idRecette) {
		this.idIngredient = idIngredient;
		this.idRecette = idRecette;
	}

	@Column(name = "idIngredient", nullable = false)
	public int getIdIngredient() {
		return this.idIngredient;
	}

	public void setIdIngredient(int idIngredient) {
		this.idIngredient = idIngredient;
	}

	@Column(name = "idRecette", nullable = false)
	public int getIdRecette() {
		return this.idRecette;
	}

	public void setIdRecette(int idRecette) {
		this.idRecette = idRecette;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof DetailRecetteId))
			return false;
		DetailRecetteId castOther = (DetailRecetteId) other;

		return (this.getIdIngredient() == castOther.getIdIngredient())
				&& (this.getIdRecette() == castOther.getIdRecette());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdIngredient();
		result = 37 * result + this.getIdRecette();
		return result;
	}

}
