package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CDetailrecette generated by hbm2java
 */
@Entity
@Table(name = "c_detailrecette", catalog = "gestion_resto2")
public class DetailRecette implements java.io.Serializable {

	private DetailRecetteId id;
	private Recette CRecette;
	private Ingredient CIngredient;
	private int quantite;
	private String unite;

	public DetailRecette() {
	}

	public DetailRecette(DetailRecetteId id, Recette CRecette,
			Ingredient CIngredient, int quantite, String unite) {
		this.id = id;
		this.CRecette = CRecette;
		this.CIngredient = CIngredient;
		this.quantite = quantite;
		this.unite = unite;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idIngredient", column = @Column(name = "idIngredient", nullable = false)),
			@AttributeOverride(name = "idRecette", column = @Column(name = "idRecette", nullable = false)) })
	public DetailRecetteId getId() {
		return this.id;
	}

	public void setId(DetailRecetteId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecette", nullable = false, insertable = false, updatable = false)
	public Recette getCRecette() {
		return this.CRecette;
	}

	public void setCRecette(Recette CRecette) {
		this.CRecette = CRecette;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idIngredient", nullable = false, insertable = false, updatable = false)
	public Ingredient getCIngredient() {
		return this.CIngredient;
	}

	public void setCIngredient(Ingredient CIngredient) {
		this.CIngredient = CIngredient;
	}

	@Column(name = "quantite", nullable = false)
	public int getQuantite() {
		return this.quantite;
	}

	public void setQuantite(int quantite) {
		this.quantite = quantite;
	}

	@Column(name = "unite", nullable = false, length = 10)
	public String getUnite() {
		return this.unite;
	}

	public void setUnite(String unite) {
		this.unite = unite;
	}

}
