package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * CIdentifiant generated by hbm2java
 */
@Entity
@Table(name = "c_identifiant", catalog = "gestion_resto2", uniqueConstraints = @UniqueConstraint(columnNames = {
		"login", "password" }))
public class Identifiant implements java.io.Serializable {

	private int idMembre;
	private Membre CMembre;
	private String login;
	private String password;

	public Identifiant() {
	}

	public Identifiant(Membre CMembre, String login, String password) {
		this.CMembre = CMembre;
		this.login = login;
		this.password = password;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "CMembre"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idMembre", unique = true, nullable = false)
	public int getIdMembre() {
		return this.idMembre;
	}

	public void setIdMembre(int idMembre) {
		this.idMembre = idMembre;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Membre getCMembre() {
		return this.CMembre;
	}

	public void setCMembre(Membre CMembre) {
		this.CMembre = CMembre;
	}

	@Column(name = "login", nullable = false, length = 10)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", nullable = false, length = 44)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

}
