package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CIngredient generated by hbm2java
 */
@Entity
@Table(name = "c_ingredient", catalog = "gestion_resto2")
public class Ingredient implements java.io.Serializable {

	private Integer idIngredient;
	private CatIngredient CCatingredient;
	private String nomIngredient;
	private String packaging;
	private Set<Saison> CSaisons = new HashSet<Saison>(0);
	private Set<DetailRecette> CDetailrecettes = new HashSet<DetailRecette>(0);

	public Ingredient() {
	}

	public Ingredient(CatIngredient CCatingredient, String nomIngredient,
			String packaging) {
		this.CCatingredient = CCatingredient;
		this.nomIngredient = nomIngredient;
		this.packaging = packaging;
	}

	public Ingredient(CatIngredient CCatingredient, String nomIngredient,
			String packaging, Set<Saison> CSaisons,
			Set<DetailRecette> CDetailrecettes) {
		this.CCatingredient = CCatingredient;
		this.nomIngredient = nomIngredient;
		this.packaging = packaging;
		this.CSaisons = CSaisons;
		this.CDetailrecettes = CDetailrecettes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idIngredient", unique = true, nullable = false)
	public Integer getIdIngredient() {
		return this.idIngredient;
	}

	public void setIdIngredient(Integer idIngredient) {
		this.idIngredient = idIngredient;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idCatIngredient", nullable = false)
	public CatIngredient getCCatingredient() {
		return this.CCatingredient;
	}

	public void setCCatingredient(CatIngredient CCatingredient) {
		this.CCatingredient = CCatingredient;
	}

	@Column(name = "nomIngredient", nullable = false, length = 100)
	public String getNomIngredient() {
		return this.nomIngredient;
	}

	public void setNomIngredient(String nomIngredient) {
		this.nomIngredient = nomIngredient;
	}

	@Column(name = "packaging", nullable = false, length = 20)
	public String getPackaging() {
		return this.packaging;
	}

	public void setPackaging(String packaging) {
		this.packaging = packaging;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "c_ing_saison", catalog = "gestion_resto2", joinColumns = { @JoinColumn(name = "idIngredient", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idSaison", nullable = false, updatable = false) })
	public Set<Saison> getCSaisons() {
		return this.CSaisons;
	}

	public void setCSaisons(Set<Saison> CSaisons) {
		this.CSaisons = CSaisons;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CIngredient")
	public Set<DetailRecette> getCDetailrecettes() {
		return this.CDetailrecettes;
	}

	public void setCDetailrecettes(Set<DetailRecette> CDetailrecettes) {
		this.CDetailrecettes = CDetailrecettes;
	}

}
