package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CMembre generated by hbm2java
 */
@Entity
@Table(name = "c_membre", catalog = "gestion_resto2")
public class Membre implements java.io.Serializable {

	private Integer idMembre;
	private String nom;
	private String prenom;
	private String email;
	private char sexe;
	private String avatar;
	private Date dateInscription;
	private boolean statut;
	private Identifiant CIdentifiant;
	private Set<Commentaire> CCommentaires = new HashSet<Commentaire>(0);
	private Set<Recette> CRecettes = new HashSet<Recette>(0);

	public Membre() {
	}

	public Membre(String nom, String prenom, String email, char sexe,
			String avatar, Date dateInscription, boolean statut) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.sexe = sexe;
		this.avatar = avatar;
		this.dateInscription = dateInscription;
		this.statut = statut;
	}

	public Membre(String nom, String prenom, String email, char sexe,
			String avatar, Date dateInscription, boolean statut,
			Identifiant CIdentifiant, Set<Commentaire> CCommentaires,
			Set<Recette> CRecettes) {
		this.nom = nom;
		this.prenom = prenom;
		this.email = email;
		this.sexe = sexe;
		this.avatar = avatar;
		this.dateInscription = dateInscription;
		this.statut = statut;
		this.CIdentifiant = CIdentifiant;
		this.CCommentaires = CCommentaires;
		this.CRecettes = CRecettes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMembre", unique = true, nullable = false)
	public Integer getIdMembre() {
		return this.idMembre;
	}

	public void setIdMembre(Integer idMembre) {
		this.idMembre = idMembre;
	}

	@Column(name = "nom", nullable = false, length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", nullable = false, length = 50)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "sexe", nullable = false, length = 1)
	public char getSexe() {
		return this.sexe;
	}

	public void setSexe(char sexe) {
		this.sexe = sexe;
	}

	@Column(name = "avatar", nullable = false, length = 50)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateInscription", nullable = false, length = 19)
	public Date getDateInscription() {
		return this.dateInscription;
	}

	public void setDateInscription(Date dateInscription) {
		this.dateInscription = dateInscription;
	}

	@Column(name = "statut", nullable = false)
	public boolean isStatut() {
		return this.statut;
	}

	public void setStatut(boolean statut) {
		this.statut = statut;
	}

	@OneToOne(fetch = FetchType.LAZY, mappedBy = "CMembre")
	public Identifiant getCIdentifiant() {
		return this.CIdentifiant;
	}

	public void setCIdentifiant(Identifiant CIdentifiant) {
		this.CIdentifiant = CIdentifiant;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CMembre")
	public Set<Commentaire> getCCommentaires() {
		return this.CCommentaires;
	}

	public void setCCommentaires(Set<Commentaire> CCommentaires) {
		this.CCommentaires = CCommentaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "CMembre")
	public Set<Recette> getCRecettes() {
		return this.CRecettes;
	}

	public void setCRecettes(Set<Recette> CRecettes) {
		this.CRecettes = CRecettes;
	}

}
