package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CPhoto generated by hbm2java
 */
@Entity
@Table(name = "c_photo", catalog = "gestion_resto2")
public class Photo implements java.io.Serializable {

	private Integer idPhoto;
	private Recette CRecette;
	private String nomPhoto;
	private String pathPhoto;
	private int taille;
	private String format;

	public Photo() {
	}

	public Photo(Recette CRecette, String nomPhoto, String pathPhoto,
			int taille, String format) {
		this.CRecette = CRecette;
		this.nomPhoto = nomPhoto;
		this.pathPhoto = pathPhoto;
		this.taille = taille;
		this.format = format;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPhoto", unique = true, nullable = false)
	public Integer getIdPhoto() {
		return this.idPhoto;
	}

	public void setIdPhoto(Integer idPhoto) {
		this.idPhoto = idPhoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRecette", nullable = false)
	public Recette getCRecette() {
		return this.CRecette;
	}

	public void setCRecette(Recette CRecette) {
		this.CRecette = CRecette;
	}

	@Column(name = "nomPhoto", nullable = false, length = 50)
	public String getNomPhoto() {
		return this.nomPhoto;
	}

	public void setNomPhoto(String nomPhoto) {
		this.nomPhoto = nomPhoto;
	}

	@Column(name = "pathPhoto", nullable = false, length = 50)
	public String getPathPhoto() {
		return this.pathPhoto;
	}

	public void setPathPhoto(String pathPhoto) {
		this.pathPhoto = pathPhoto;
	}

	@Column(name = "taille", nullable = false)
	public int getTaille() {
		return this.taille;
	}

	public void setTaille(int taille) {
		this.taille = taille;
	}

	@Column(name = "format", nullable = false, length = 10)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

}
