package pojo.recette;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * CTheme generated by hbm2java
 */
@Entity
@Table(name = "c_theme", catalog = "gestion_resto2")
public class ThemeRecette implements java.io.Serializable {

	private Integer idTheme;
	private String theme;
	private Set<Recette> CRecettes = new HashSet<Recette>(0);

	public ThemeRecette() {
	}

	public ThemeRecette(String theme) {
		this.theme = theme;
	}

	public ThemeRecette(String theme, Set<Recette> CRecettes) {
		this.theme = theme;
		this.CRecettes = CRecettes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTheme", unique = true, nullable = false)
	public Integer getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(Integer idTheme) {
		this.idTheme = idTheme;
	}

	@Column(name = "theme", nullable = false, length = 50)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "CThemes")
	public Set<Recette> getCRecettes() {
		return this.CRecettes;
	}

	public void setCRecettes(Set<Recette> CRecettes) {
		this.CRecettes = CRecettes;
	}

}
