package pojo.forum;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FMessage generated by hbm2java
 */
@Entity
@Table(name = "f_message", catalog = "gestion_resto2")
public class Message implements java.io.Serializable {

	private Integer idMessage;
	private Topic FTopic;
	private Message FMessage;
	private Utilisateur FUtilisateur;
	private String message;
	private Date dateInsertion;
	private Set<Message> FMessages = new HashSet<Message>(0);

	public Message() {
	}

	public Message(Topic FTopic, Message FMessage,
			Utilisateur FUtilisateur, String message, Date dateInsertion) {
		this.FTopic = FTopic;
		this.FMessage = FMessage;
		this.FUtilisateur = FUtilisateur;
		this.message = message;
		this.dateInsertion = dateInsertion;
	}

	public Message(Topic FTopic, Message FMessage,
			Utilisateur FUtilisateur, String message, Date dateInsertion,
			Set<Message> FMessages) {
		this.FTopic = FTopic;
		this.FMessage = FMessage;
		this.FUtilisateur = FUtilisateur;
		this.message = message;
		this.dateInsertion = dateInsertion;
		this.FMessages = FMessages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idMessage", unique = true, nullable = false)
	public Integer getIdMessage() {
		return this.idMessage;
	}

	public void setIdMessage(Integer idMessage) {
		this.idMessage = idMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTopic", nullable = false)
	public Topic getFTopic() {
		return this.FTopic;
	}

	public void setFTopic(Topic FTopic) {
		this.FTopic = FTopic;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "message_idMessage", nullable = false)
	public Message getFMessage() {
		return this.FMessage;
	}

	public void setFMessage(Message FMessage) {
		this.FMessage = FMessage;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idUtilisateur", nullable = false)
	public Utilisateur getFUtilisateur() {
		return this.FUtilisateur;
	}

	public void setFUtilisateur(Utilisateur FUtilisateur) {
		this.FUtilisateur = FUtilisateur;
	}

	@Column(name = "message", nullable = false)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateInsertion", nullable = false, length = 19)
	public Date getDateInsertion() {
		return this.dateInsertion;
	}

	public void setDateInsertion(Date dateInsertion) {
		this.dateInsertion = dateInsertion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FMessage")
	public Set<Message> getFMessages() {
		return this.FMessages;
	}

	public void setFMessages(Set<Message> FMessages) {
		this.FMessages = FMessages;
	}

}
