package pojo.forum;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * FTheme generated by hbm2java
 */
@Entity
@Table(name = "f_theme", catalog = "gestion_resto2")
public class ThemeForum implements java.io.Serializable {

	private Integer idTheme;
	private ThemeForum FTheme;
	private String theme;
	private Set<Topic> FTopics = new HashSet<Topic>(0);
	private Set<ThemeForum> FThemes = new HashSet<ThemeForum>(0);

	public ThemeForum() {
	}

	public ThemeForum(ThemeForum FTheme, String theme) {
		this.FTheme = FTheme;
		this.theme = theme;
	}

	public ThemeForum(ThemeForum FTheme, String theme, Set<Topic> FTopics,
			Set<ThemeForum> FThemes) {
		this.FTheme = FTheme;
		this.theme = theme;
		this.FTopics = FTopics;
		this.FThemes = FThemes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTheme", unique = true, nullable = false)
	public Integer getIdTheme() {
		return this.idTheme;
	}

	public void setIdTheme(Integer idTheme) {
		this.idTheme = idTheme;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "theme_idTheme", nullable = false)
	public ThemeForum getFTheme() {
		return this.FTheme;
	}

	public void setFTheme(ThemeForum FTheme) {
		this.FTheme = FTheme;
	}

	@Column(name = "theme", nullable = false, length = 50)
	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FTheme")
	public Set<Topic> getFTopics() {
		return this.FTopics;
	}

	public void setFTopics(Set<Topic> FTopics) {
		this.FTopics = FTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FTheme")
	public Set<ThemeForum> getFThemes() {
		return this.FThemes;
	}

	public void setFThemes(Set<ThemeForum> FThemes) {
		this.FThemes = FThemes;
	}

}
