package pojo.forum;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FUtilisateur generated by hbm2java
 */
@Entity
@Table(name = "f_utilisateur", catalog = "gestion_resto2")
public class Utilisateur implements java.io.Serializable {

	private Integer idUtilisateur;
	private String nickName;
	private String avatar;
	private String email;
	private boolean statut;
	private Date dateInsertion;
	private Set<Topic> FTopics = new HashSet<Topic>(0);
	private Set<Message> FMessages = new HashSet<Message>(0);

	public Utilisateur() {
	}

	public Utilisateur(String nickName, String avatar, String email,
			boolean statut, Date dateInsertion) {
		this.nickName = nickName;
		this.avatar = avatar;
		this.email = email;
		this.statut = statut;
		this.dateInsertion = dateInsertion;
	}

	public Utilisateur(String nickName, String avatar, String email,
			boolean statut, Date dateInsertion, Set<Topic> FTopics,
			Set<Message> FMessages) {
		this.nickName = nickName;
		this.avatar = avatar;
		this.email = email;
		this.statut = statut;
		this.dateInsertion = dateInsertion;
		this.FTopics = FTopics;
		this.FMessages = FMessages;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idUtilisateur", unique = true, nullable = false)
	public Integer getIdUtilisateur() {
		return this.idUtilisateur;
	}

	public void setIdUtilisateur(Integer idUtilisateur) {
		this.idUtilisateur = idUtilisateur;
	}

	@Column(name = "nickName", nullable = false, length = 50)
	public String getNickName() {
		return this.nickName;
	}

	public void setNickName(String nickName) {
		this.nickName = nickName;
	}

	@Column(name = "avatar", nullable = false, length = 50)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "email", nullable = false, length = 50)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "statut", nullable = false)
	public boolean isStatut() {
		return this.statut;
	}

	public void setStatut(boolean statut) {
		this.statut = statut;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateInsertion", nullable = false, length = 19)
	public Date getDateInsertion() {
		return this.dateInsertion;
	}

	public void setDateInsertion(Date dateInsertion) {
		this.dateInsertion = dateInsertion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FUtilisateur")
	public Set<Topic> getFTopics() {
		return this.FTopics;
	}

	public void setFTopics(Set<Topic> FTopics) {
		this.FTopics = FTopics;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "FUtilisateur")
	public Set<Message> getFMessages() {
		return this.FMessages;
	}

	public void setFMessages(Set<Message> FMessages) {
		this.FMessages = FMessages;
	}

}
