package pojo.livre;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * LAuteur generated by hbm2java
 */
@Entity
@Table(name = "l_auteur", catalog = "gestion_resto2")
public class Auteur implements java.io.Serializable {

	private Integer idAuteur;
	private String nomAuteur;
	private String prenomAuteur;
	private String emailAuteur;
	private Set<Livre> LLivres = new HashSet<Livre>(0);

	public Auteur() {
	}

	public Auteur(String nomAuteur, String prenomAuteur, String emailAuteur) {
		this.nomAuteur = nomAuteur;
		this.prenomAuteur = prenomAuteur;
		this.emailAuteur = emailAuteur;
	}

	public Auteur(String nomAuteur, String prenomAuteur, String emailAuteur,
			Set<Livre> LLivres) {
		this.nomAuteur = nomAuteur;
		this.prenomAuteur = prenomAuteur;
		this.emailAuteur = emailAuteur;
		this.LLivres = LLivres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idAuteur", unique = true, nullable = false)
	public Integer getIdAuteur() {
		return this.idAuteur;
	}

	public void setIdAuteur(Integer idAuteur) {
		this.idAuteur = idAuteur;
	}

	@Column(name = "nomAuteur", nullable = false, length = 100)
	public String getNomAuteur() {
		return this.nomAuteur;
	}

	public void setNomAuteur(String nomAuteur) {
		this.nomAuteur = nomAuteur;
	}

	@Column(name = "prenomAuteur", nullable = false, length = 100)
	public String getPrenomAuteur() {
		return this.prenomAuteur;
	}

	public void setPrenomAuteur(String prenomAuteur) {
		this.prenomAuteur = prenomAuteur;
	}

	@Column(name = "emailAuteur", nullable = false, length = 100)
	public String getEmailAuteur() {
		return this.emailAuteur;
	}

	public void setEmailAuteur(String emailAuteur) {
		this.emailAuteur = emailAuteur;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "l_auteur_livre", catalog = "gestion_resto2", joinColumns = { @JoinColumn(name = "idAuteur", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idLivre", nullable = false, updatable = false) })
	public Set<Livre> getLLivres() {
		return this.LLivres;
	}

	public void setLLivres(Set<Livre> LLivres) {
		this.LLivres = LLivres;
	}

}
