package pojo.livre;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LCategorielivre generated by hbm2java
 */
@Entity
@Table(name = "l_categorielivre", catalog = "gestion_resto2")
public class CategorieLivre implements java.io.Serializable {

	private Integer idCategorieLivre;
	private String nomCategorie;
	private Set<Livre> LLivres = new HashSet<Livre>(0);

	public CategorieLivre() {
	}

	public CategorieLivre(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	public CategorieLivre(String nomCategorie, Set<Livre> LLivres) {
		this.nomCategorie = nomCategorie;
		this.LLivres = LLivres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCategorieLivre", unique = true, nullable = false)
	public Integer getIdCategorieLivre() {
		return this.idCategorieLivre;
	}

	public void setIdCategorieLivre(Integer idCategorieLivre) {
		this.idCategorieLivre = idCategorieLivre;
	}

	@Column(name = "nomCategorie", nullable = false, length = 100)
	public String getNomCategorie() {
		return this.nomCategorie;
	}

	public void setNomCategorie(String nomCategorie) {
		this.nomCategorie = nomCategorie;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LCategorielivre")
	public Set<Livre> getLLivres() {
		return this.LLivres;
	}

	public void setLLivres(Set<Livre> LLivres) {
		this.LLivres = LLivres;
	}

}
