package pojo.livre;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pojo.common.Personne;

/**
 * LCommentaire generated by hbm2java
 */
@Entity
@Table(name = "l_commentaire", catalog = "gestion_resto2")
public class CommentaireLivre implements java.io.Serializable {

	private Integer idCommentaire;
	private Personne personne;
	private Livre LLivre;
	private String commentaire;
	private Date dateCommentaire;
	private boolean statut;

	public CommentaireLivre() {
	}

	public CommentaireLivre(Personne personne, Livre LLivre, String commentaire,
			Date dateCommentaire, boolean statut) {
		this.personne = personne;
		this.LLivre = LLivre;
		this.commentaire = commentaire;
		this.dateCommentaire = dateCommentaire;
		this.statut = statut;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idCommentaire", unique = true, nullable = false)
	public Integer getIdCommentaire() {
		return this.idCommentaire;
	}

	public void setIdCommentaire(Integer idCommentaire) {
		this.idCommentaire = idCommentaire;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersonne", nullable = false)
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLivre", nullable = false)
	public Livre getLLivre() {
		return this.LLivre;
	}

	public void setLLivre(Livre LLivre) {
		this.LLivre = LLivre;
	}

	@Column(name = "commentaire", nullable = false)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateCommentaire", nullable = false, length = 19)
	public Date getDateCommentaire() {
		return this.dateCommentaire;
	}

	public void setDateCommentaire(Date dateCommentaire) {
		this.dateCommentaire = dateCommentaire;
	}

	@Column(name = "statut", nullable = false)
	public boolean isStatut() {
		return this.statut;
	}

	public void setStatut(boolean statut) {
		this.statut = statut;
	}

}
