package pojo.livre;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * LEdition generated by hbm2java
 */
@Entity
@Table(name = "l_edition", catalog = "gestion_resto2")
public class Edition implements java.io.Serializable {

	private Integer idEdition;
	private String maisonEdition;
	private String adresse;
	private String siteEdition;
	private String telephone;
	private String fax;
	private Set<Livre> LLivres = new HashSet<Livre>(0);

	public Edition() {
	}

	public Edition(String maisonEdition, String adresse, String siteEdition,
			String telephone, String fax) {
		this.maisonEdition = maisonEdition;
		this.adresse = adresse;
		this.siteEdition = siteEdition;
		this.telephone = telephone;
		this.fax = fax;
	}

	public Edition(String maisonEdition, String adresse, String siteEdition,
			String telephone, String fax, Set<Livre> LLivres) {
		this.maisonEdition = maisonEdition;
		this.adresse = adresse;
		this.siteEdition = siteEdition;
		this.telephone = telephone;
		this.fax = fax;
		this.LLivres = LLivres;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idEdition", unique = true, nullable = false)
	public Integer getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(Integer idEdition) {
		this.idEdition = idEdition;
	}

	@Column(name = "maisonEdition", nullable = false, length = 50)
	public String getMaisonEdition() {
		return this.maisonEdition;
	}

	public void setMaisonEdition(String maisonEdition) {
		this.maisonEdition = maisonEdition;
	}

	@Column(name = "adresse", nullable = false, length = 256)
	public String getAdresse() {
		return this.adresse;
	}

	public void setAdresse(String adresse) {
		this.adresse = adresse;
	}

	@Column(name = "siteEdition", nullable = false, length = 50)
	public String getSiteEdition() {
		return this.siteEdition;
	}

	public void setSiteEdition(String siteEdition) {
		this.siteEdition = siteEdition;
	}

	@Column(name = "telephone", nullable = false, length = 15)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "fax", nullable = false, length = 15)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "LEdition")
	public Set<Livre> getLLivres() {
		return this.LLivres;
	}

	public void setLLivres(Set<Livre> LLivres) {
		this.LLivres = LLivres;
	}

}
