package pojo.common;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import pojo.forum.Topic;
import pojo.recette.Commentaire;
import pojo.recette.Recette;

/**
 * Moderateur generated by hbm2java
 */
@Entity
@Table(name = "moderateur", catalog = "gestion_resto2")
public class Moderateur implements java.io.Serializable {

	private int idPersonne;
	private Personne personne;
	private Set<Commentaire> CCommentaires = new HashSet<Commentaire>(0);
	private Set<Recette> CRecettes = new HashSet<Recette>(0);
	private Set<Topic> FTopics = new HashSet<Topic>(0);

	public Moderateur() {
	}

	public Moderateur(Personne personne) {
		this.personne = personne;
	}

	public Moderateur(Personne personne, Set<Commentaire> CCommentaires,
			Set<Recette> CRecettes, Set<Topic> FTopics) {
		this.personne = personne;
		this.CCommentaires = CCommentaires;
		this.CRecettes = CRecettes;
		this.FTopics = FTopics;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personne"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idPersonne", unique = true, nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moderateur")
	public Set<Commentaire> getCCommentaires() {
		return this.CCommentaires;
	}

	public void setCCommentaires(Set<Commentaire> CCommentaires) {
		this.CCommentaires = CCommentaires;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moderateur")
	public Set<Recette> getCRecettes() {
		return this.CRecettes;
	}

	public void setCRecettes(Set<Recette> CRecettes) {
		this.CRecettes = CRecettes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "moderateur")
	public Set<Topic> getFTopics() {
		return this.FTopics;
	}

	public void setFTopics(Set<Topic> FTopics) {
		this.FTopics = FTopics;
	}

}
