package pojo.common;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import pojo.livre.Livre;

/**
 * Responsableediteur generated by hbm2java
 */
@Entity
@Table(name = "responsableediteur", catalog = "gestion_resto2")
public class ResponsableEditeur implements java.io.Serializable {

	private int idPersonne;
	private Personne personne;
	private Set<Livre> LLivres = new HashSet<Livre>(0);

	public ResponsableEditeur() {
	}

	public ResponsableEditeur(Personne personne) {
		this.personne = personne;
	}

	public ResponsableEditeur(Personne personne, Set<Livre> LLivres) {
		this.personne = personne;
		this.LLivres = LLivres;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "personne"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "idPersonne", unique = true, nullable = false)
	public int getIdPersonne() {
		return this.idPersonne;
	}

	public void setIdPersonne(int idPersonne) {
		this.idPersonne = idPersonne;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Personne getPersonne() {
		return this.personne;
	}

	public void setPersonne(Personne personne) {
		this.personne = personne;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsableediteur")
	public Set<Livre> getLLivres() {
		return this.LLivres;
	}

	public void setLLivres(Set<Livre> LLivres) {
		this.LLivres = LLivres;
	}

}
