package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RArrondissement generated by hbm2java
 */
@Entity
@Table(name = "r_arrondissement", catalog = "gestion_resto2")
public class Arrondissement implements java.io.Serializable {

	private Integer idArrondissement;
	private String nomArrondissement;
	private Set<Restaurant> RRestaurants = new HashSet<Restaurant>(0);

	public Arrondissement() {
	}

	public Arrondissement(String nomArrondissement) {
		this.nomArrondissement = nomArrondissement;
	}

	public Arrondissement(String nomArrondissement,
			Set<Restaurant> RRestaurants) {
		this.nomArrondissement = nomArrondissement;
		this.RRestaurants = RRestaurants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idArrondissement", unique = true, nullable = false)
	public Integer getIdArrondissement() {
		return this.idArrondissement;
	}

	public void setIdArrondissement(Integer idArrondissement) {
		this.idArrondissement = idArrondissement;
	}

	@Column(name = "nomArrondissement", nullable = false, length = 50)
	public String getNomArrondissement() {
		return this.nomArrondissement;
	}

	public void setNomArrondissement(String nomArrondissement) {
		this.nomArrondissement = nomArrondissement;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RArrondissement")
	public Set<Restaurant> getRRestaurants() {
		return this.RRestaurants;
	}

	public void setRRestaurants(Set<Restaurant> RRestaurants) {
		this.RRestaurants = RRestaurants;
	}

}
