package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * RCuisine generated by hbm2java
 */
@Entity
@Table(name = "r_cuisine", catalog = "gestion_resto2")
public class Cuisine implements java.io.Serializable {

	private Integer idTypeCuisine;
	private String typeCuisine;
	private Set<Restaurant> RRestaurants = new HashSet<Restaurant>(0);

	public Cuisine() {
	}

	public Cuisine(String typeCuisine) {
		this.typeCuisine = typeCuisine;
	}

	public Cuisine(String typeCuisine, Set<Restaurant> RRestaurants) {
		this.typeCuisine = typeCuisine;
		this.RRestaurants = RRestaurants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idTypeCuisine", unique = true, nullable = false)
	public Integer getIdTypeCuisine() {
		return this.idTypeCuisine;
	}

	public void setIdTypeCuisine(Integer idTypeCuisine) {
		this.idTypeCuisine = idTypeCuisine;
	}

	@Column(name = "typeCuisine", nullable = false, length = 50)
	public String getTypeCuisine() {
		return this.typeCuisine;
	}

	public void setTypeCuisine(String typeCuisine) {
		this.typeCuisine = typeCuisine;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "r_cuisine_resto", catalog = "gestion_resto2", joinColumns = { @JoinColumn(name = "idTypeCuisine", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idRestaurant", nullable = false, updatable = false) })
	public Set<Restaurant> getRRestaurants() {
		return this.RRestaurants;
	}

	public void setRRestaurants(Set<Restaurant> RRestaurants) {
		this.RRestaurants = RRestaurants;
	}

}
