package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RLocalite generated by hbm2java
 */
@Entity
@Table(name = "r_localite", catalog = "gestion_resto2")
public class Localite implements java.io.Serializable {

	private Integer idLocalite;
	private String codePostal;
	private String localite;
	private Set<Restaurant> RRestaurants = new HashSet<Restaurant>(0);

	public Localite() {
	}

	public Localite(String codePostal, String localite) {
		this.codePostal = codePostal;
		this.localite = localite;
	}

	public Localite(String codePostal, String localite,
			Set<Restaurant> RRestaurants) {
		this.codePostal = codePostal;
		this.localite = localite;
		this.RRestaurants = RRestaurants;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idLocalite", unique = true, nullable = false)
	public Integer getIdLocalite() {
		return this.idLocalite;
	}

	public void setIdLocalite(Integer idLocalite) {
		this.idLocalite = idLocalite;
	}

	@Column(name = "codePostal", nullable = false, length = 5)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "localite", nullable = false, length = 50)
	public String getLocalite() {
		return this.localite;
	}

	public void setLocalite(String localite) {
		this.localite = localite;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RLocalite")
	public Set<Restaurant> getRRestaurants() {
		return this.RRestaurants;
	}

	public void setRRestaurants(Set<Restaurant> RRestaurants) {
		this.RRestaurants = RRestaurants;
	}

}
