package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RPhoto generated by hbm2java
 */
@Entity
@Table(name = "r_photo", catalog = "gestion_resto2")
public class PhotoResto implements java.io.Serializable {

	private Integer idPhoto;
	private Restaurant RRestaurant;
	private String nomPhoto;
	private String pathPhoto;
	private String format;
	private int taille;

	public PhotoResto() {
	}

	public PhotoResto(Restaurant RRestaurant, String nomPhoto, String pathPhoto,
			String format, int taille) {
		this.RRestaurant = RRestaurant;
		this.nomPhoto = nomPhoto;
		this.pathPhoto = pathPhoto;
		this.format = format;
		this.taille = taille;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPhoto", unique = true, nullable = false)
	public Integer getIdPhoto() {
		return this.idPhoto;
	}

	public void setIdPhoto(Integer idPhoto) {
		this.idPhoto = idPhoto;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRestaurant", nullable = false)
	public Restaurant getRRestaurant() {
		return this.RRestaurant;
	}

	public void setRRestaurant(Restaurant RRestaurant) {
		this.RRestaurant = RRestaurant;
	}

	@Column(name = "nomPhoto", nullable = false, length = 50)
	public String getNomPhoto() {
		return this.nomPhoto;
	}

	public void setNomPhoto(String nomPhoto) {
		this.nomPhoto = nomPhoto;
	}

	@Column(name = "pathPhoto", nullable = false, length = 50)
	public String getPathPhoto() {
		return this.pathPhoto;
	}

	public void setPathPhoto(String pathPhoto) {
		this.pathPhoto = pathPhoto;
	}

	@Column(name = "format", nullable = false, length = 10)
	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	@Column(name = "taille", nullable = false)
	public int getTaille() {
		return this.taille;
	}

	public void setTaille(int taille) {
		this.taille = taille;
	}

}
