package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import pojo.common.Administrateur;

/**
 * RRestaurant generated by hbm2java
 */
@Entity
@Table(name = "r_restaurant", catalog = "gestion_resto2")
public class Restaurant implements java.io.Serializable {

	private Integer idRestaurant;
	private Restaurateur RRestaurateur;
	private Administrateur administrateur;
	private Arrondissement RArrondissement;
	private Localite RLocalite;
	private String nomResto;
	private String nrRue;
	private Date dateEncodage;
	private String telephone;
	private String siteWeb;
	private String latitude;
	private String longitude;
	private byte cotisation;
	private byte statut;
	private byte nbServices;
	private String commentaire;
	private Set<Cuisine> RCuisines = new HashSet<Cuisine>(0);
	private Set<PhotoResto> RPhotos = new HashSet<PhotoResto>(0);
	private Set<Specialite> RSpecialites = new HashSet<Specialite>(0);

	public Restaurant() {
	}

	public Restaurant(Restaurateur RRestaurateur,
			Administrateur administrateur, Arrondissement RArrondissement,
			Localite RLocalite, String nomResto, String nrRue,
			Date dateEncodage, String telephone, String siteWeb,
			String latitude, String longitude, byte cotisation, byte statut,
			byte nbServices, String commentaire) {
		this.RRestaurateur = RRestaurateur;
		this.administrateur = administrateur;
		this.RArrondissement = RArrondissement;
		this.RLocalite = RLocalite;
		this.nomResto = nomResto;
		this.nrRue = nrRue;
		this.dateEncodage = dateEncodage;
		this.telephone = telephone;
		this.siteWeb = siteWeb;
		this.latitude = latitude;
		this.longitude = longitude;
		this.cotisation = cotisation;
		this.statut = statut;
		this.nbServices = nbServices;
		this.commentaire = commentaire;
	}

	public Restaurant(Restaurateur RRestaurateur,
			Administrateur administrateur, Arrondissement RArrondissement,
			Localite RLocalite, String nomResto, String nrRue,
			Date dateEncodage, String telephone, String siteWeb,
			String latitude, String longitude, byte cotisation, byte statut,
			byte nbServices, String commentaire, Set<Cuisine> RCuisines,
			Set<PhotoResto> RPhotos, Set<Specialite> RSpecialites) {
		this.RRestaurateur = RRestaurateur;
		this.administrateur = administrateur;
		this.RArrondissement = RArrondissement;
		this.RLocalite = RLocalite;
		this.nomResto = nomResto;
		this.nrRue = nrRue;
		this.dateEncodage = dateEncodage;
		this.telephone = telephone;
		this.siteWeb = siteWeb;
		this.latitude = latitude;
		this.longitude = longitude;
		this.cotisation = cotisation;
		this.statut = statut;
		this.nbServices = nbServices;
		this.commentaire = commentaire;
		this.RCuisines = RCuisines;
		this.RPhotos = RPhotos;
		this.RSpecialites = RSpecialites;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idRestaurant", unique = true, nullable = false)
	public Integer getIdRestaurant() {
		return this.idRestaurant;
	}

	public void setIdRestaurant(Integer idRestaurant) {
		this.idRestaurant = idRestaurant;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idRestaurateur", nullable = false)
	public Restaurateur getRRestaurateur() {
		return this.RRestaurateur;
	}

	public void setRRestaurateur(Restaurateur RRestaurateur) {
		this.RRestaurateur = RRestaurateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersonne", nullable = false)
	public Administrateur getAdministrateur() {
		return this.administrateur;
	}

	public void setAdministrateur(Administrateur administrateur) {
		this.administrateur = administrateur;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idArrondissement", nullable = false)
	public Arrondissement getRArrondissement() {
		return this.RArrondissement;
	}

	public void setRArrondissement(Arrondissement RArrondissement) {
		this.RArrondissement = RArrondissement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idLocalite", nullable = false)
	public Localite getRLocalite() {
		return this.RLocalite;
	}

	public void setRLocalite(Localite RLocalite) {
		this.RLocalite = RLocalite;
	}

	@Column(name = "nomResto", nullable = false, length = 50)
	public String getNomResto() {
		return this.nomResto;
	}

	public void setNomResto(String nomResto) {
		this.nomResto = nomResto;
	}

	@Column(name = "nr_rue", nullable = false, length = 100)
	public String getNrRue() {
		return this.nrRue;
	}

	public void setNrRue(String nrRue) {
		this.nrRue = nrRue;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dateEncodage", nullable = false, length = 19)
	public Date getDateEncodage() {
		return this.dateEncodage;
	}

	public void setDateEncodage(Date dateEncodage) {
		this.dateEncodage = dateEncodage;
	}

	@Column(name = "telephone", nullable = false, length = 15)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

	@Column(name = "siteWeb", nullable = false, length = 50)
	public String getSiteWeb() {
		return this.siteWeb;
	}

	public void setSiteWeb(String siteWeb) {
		this.siteWeb = siteWeb;
	}

	@Column(name = "latitude", nullable = false, length = 10)
	public String getLatitude() {
		return this.latitude;
	}

	public void setLatitude(String latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", nullable = false, length = 10)
	public String getLongitude() {
		return this.longitude;
	}

	public void setLongitude(String longitude) {
		this.longitude = longitude;
	}

	@Column(name = "cotisation", nullable = false)
	public byte getCotisation() {
		return this.cotisation;
	}

	public void setCotisation(byte cotisation) {
		this.cotisation = cotisation;
	}

	@Column(name = "statut", nullable = false)
	public byte getStatut() {
		return this.statut;
	}

	public void setStatut(byte statut) {
		this.statut = statut;
	}

	@Column(name = "nbServices", nullable = false)
	public byte getNbServices() {
		return this.nbServices;
	}

	public void setNbServices(byte nbServices) {
		this.nbServices = nbServices;
	}

	@Column(name = "commentaire", nullable = false)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "RRestaurants")
	public Set<Cuisine> getRCuisines() {
		return this.RCuisines;
	}

	public void setRCuisines(Set<Cuisine> RCuisines) {
		this.RCuisines = RCuisines;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RRestaurant")
	public Set<PhotoResto> getRPhotos() {
		return this.RPhotos;
	}

	public void setRPhotos(Set<PhotoResto> RPhotos) {
		this.RPhotos = RPhotos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "RRestaurant")
	public Set<Specialite> getRSpecialites() {
		return this.RSpecialites;
	}

	public void setRSpecialites(Set<Specialite> RSpecialites) {
		this.RSpecialites = RSpecialites;
	}

}
