package pojo.resto;

// Generated 14-avr.-2014 13:45:30 by Hibernate Tools 4.0.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * RSpecialite generated by hbm2java
 */
@Entity
@Table(name = "r_specialite", catalog = "gestion_resto2")
public class Specialite implements java.io.Serializable {

	private Integer idSpecialite;
	private Restaurant RRestaurant;
	private String nomSpecialite;
	private String commentaire;
	private String photo;

	public Specialite() {
	}

	public Specialite(Restaurant RRestaurant, String nomSpecialite,
			String commentaire, String photo) {
		this.RRestaurant = RRestaurant;
		this.nomSpecialite = nomSpecialite;
		this.commentaire = commentaire;
		this.photo = photo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idSpecialite", unique = true, nullable = false)
	public Integer getIdSpecialite() {
		return this.idSpecialite;
	}

	public void setIdSpecialite(Integer idSpecialite) {
		this.idSpecialite = idSpecialite;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "r_idRestaurant", nullable = false)
	public Restaurant getRRestaurant() {
		return this.RRestaurant;
	}

	public void setRRestaurant(Restaurant RRestaurant) {
		this.RRestaurant = RRestaurant;
	}

	@Column(name = "nomSpecialite", nullable = false, length = 50)
	public String getNomSpecialite() {
		return this.nomSpecialite;
	}

	public void setNomSpecialite(String nomSpecialite) {
		this.nomSpecialite = nomSpecialite;
	}

	@Column(name = "commentaire", nullable = false)
	public String getCommentaire() {
		return this.commentaire;
	}

	public void setCommentaire(String commentaire) {
		this.commentaire = commentaire;
	}

	@Column(name = "photo", nullable = false, length = 50)
	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

}
